package org.jxnu.stu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jxnu.stu.controller.vo.CartProductVoList;
import org.jxnu.stu.dao.pojo.Cart;
import org.jxnu.stu.dao.pojo.CartExample;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbg.generated Sat Mar 30 17:46:04 CST 2019
     */
    int updateByPrimaryKey(Cart record);

    List<CartProductVoList> listByUserIdOrProductId(@Param("userId") Integer userId,@Param("productId") Integer productId);

    int hasUnChecked(Integer userId);

    /**
     * 在原有的quantity上加上count
     * @param userId
     * @param productId
     * @param count
     * @return
     */
    int add(@Param("userId") Integer userId,@Param("productId") Integer productId,@Param("count") Integer count);

    /**
     * 直接update quantity变为count
     * @param userId
     * @param productId
     * @param count
     * @return
     */
    int update(@Param("userId") Integer userId,@Param("productId") Integer productId,@Param("count") Integer count);

    int deleteProduct(@Param("userId") Integer userId,@Param("productIdList")List productIdList);

    int selectOrUnSelect(@Param("userId")Integer userId,@Param("productId")Integer productId,@Param("checkStatus") Integer checkStatus);

    int getCartProductCount(Integer userId);

    List<Cart> selectCheckedByUserId(Integer userId);

    int deleteAllCart(Integer userId);


}